# EDA

In [ ]:
import pandas as pd
import os
from pathlib import Path

## Obtener direcciones de archivos

In [12]:
mainPath ='../data/raw/'
dirs = []
for item in os.listdir(mainPath):
    lclPath = Path(mainPath).joinpath(item)
    for f in lclPath.glob('*.csv'):
        dirs.append(str(f))

dirs

['../data/raw/2026/datos_abiertos_2026_06.csv',
 '../data/raw/2026/datos_abiertos_2026_02.csv',
 '../data/raw/2026/datos_abiertos_2026_07.csv',
 '../data/raw/2026/datos_abiertos_2026_03.csv',
 '../data/raw/2026/datos_abiertos_2026_08.csv',
 '../data/raw/2026/datos_abiertos_2026_09.csv',
 '../data/raw/2026/datos_abiertos_2026_04.csv',
 '../data/raw/2026/datos_abiertos_2026_01.csv',
 '../data/raw/2026/datos_abiertos_2026_05.csv',
 '../data/raw/2025/datos_abiertos_2025_09.csv',
 '../data/raw/2025/datos_abiertos_2025_06.csv',
 '../data/raw/2025/datos_abiertos_2025_03.csv',
 '../data/raw/2025/datos_abiertos_2025_11.csv',
 '../data/raw/2025/datos_abiertos_2025_01.csv',
 '../data/raw/2025/datos_abiertos_2025_02.csv',
 '../data/raw/2025/datos_abiertos_2025_10.csv',
 '../data/raw/2025/datos_abiertos_2025_12.csv',
 '../data/raw/2025/datos_abiertos_2025_07.csv',
 '../data/raw/2025/datos_abiertos_2025_08.csv',
 '../data/raw/2025/datos_abiertos_2025_04.csv',
 '../data/raw/2025/datos_abiertos_2025_05.csv']

## Unificación de CSV

In [13]:
dfs = [pd.read_csv(path, encoding='latin1') for path in dirs if str(path).__contains__('datos_abiertos')]

df = pd.concat(dfs, ignore_index=True)
df.head()

,Viaje_Id,Usuario_Id,Genero,AÃ±o_de_nacimiento,Inicio_del_viaje,Fin_del_viaje,Origen_Id,Destino_Id,Año_de_nacimiento
0,44407944,252161,M,1983.0,2026-06-01 00:06:46,2026-06-01 00:09:53,16,30,NaN
1,44407945,4707664,F,1990.0,2026-06-01 00:07:19,2026-06-01 00:26:47,32,175,NaN
2,44407949,4572563,M,2003.0,2026-06-01 00:10:51,2026-06-01 00:31:56,263,270,NaN
3,44407957,4036274,M,1988.0,2026-06-01 00:15:44,2026-06-01 00:21:47,38,81,NaN
4,44407964,4711556,M,1988.0,2026-06-01 00:21:55,2026-06-01 00:35:08,26,159,NaN

## Eliminacion de columnas

Dado el objetivo de identificar la cantidad requerida por hora en los puntos de orige, hay campos que ofrecen nulo valor a la predicción. Los campos a mantener serian los tiempos de viaje (inicio y fin)  asi como el origen y destino.

In [ ]:
df.drop(columns=['AÃ±o_de_nacimiento','Año_de_nacimiento','Viaje_Id','Genero','Usuario_Id'], inplace=True)

df

/tmp/ipykernel_187696/1959731117.py:6: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop(columns=['AÃ±o_de_nacimiento','Año_de_nacimiento','Viaje_Id','Genero','Usuario_Id'], inplace=True)

            Inicio_del_viaje        Fin_del_viaje  Origen_Id  Destino_Id
0        2026-06-01 00:06:46  2026-06-01 00:09:53         16          30
1        2026-06-01 00:07:19  2026-06-01 00:26:47         32         175
2        2026-06-01 00:10:51  2026-06-01 00:31:56        263         270
3        2026-06-01 00:15:44  2026-06-01 00:21:47         38          81
4        2026-06-01 00:21:55  2026-06-01 00:35:08         26         159
...                      ...                  ...        ...         ...
7894092  2025-05-31 23:59:12  2025-06-01 00:06:32         79          69
7894093  2025-05-31 23:59:20  2025-06-01 00:17:54         70          34
7894094  2025-05-31 23:59:41  2025-06-01 00:13:55        143         233
7894095  2025-05-31 23:59:42  2025-06-01 00:10:31         75          28
7894096  2025-05-31 23:59:48  2025-06-01 00:09:10         55         376

[7894097 rows x 4 columns]

## Eliminacion de duplicados

In [5]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
df

/tmp/ipykernel_187696/3433728435.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop_duplicates is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop_duplicates(inplace=True)
/tmp/ipykernel_187696/3433728435.py:2: Pandas4Warning: The inplace keyword in DataFrame.reset_index is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.reset_index(drop=True, inplace=True)

            Inicio_del_viaje        Fin_del_viaje  Origen_Id  Destino_Id
0        2026-06-01 00:06:46  2026-06-01 00:09:53         16          30
1        2026-06-01 00:07:19  2026-06-01 00:26:47         32         175
2        2026-06-01 00:10:51  2026-06-01 00:31:56        263         270
3        2026-06-01 00:15:44  2026-06-01 00:21:47         38          81
4        2026-06-01 00:21:55  2026-06-01 00:35:08         26         159
...                      ...                  ...        ...         ...
7891822  2025-05-31 23:59:12  2025-06-01 00:06:32         79          69
7891823  2025-05-31 23:59:20  2025-06-01 00:17:54         70          34
7891824  2025-05-31 23:59:41  2025-06-01 00:13:55        143         233
7891825  2025-05-31 23:59:42  2025-06-01 00:10:31         75          28
7891826  2025-05-31 23:59:48  2025-06-01 00:09:10         55         376

[7891827 rows x 4 columns]

## Esquema inicial

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7891827 entries, 0 to 7891826
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   Inicio_del_viaje  str
 1   Fin_del_viaje     str
 2   Origen_Id         int64
 3   Destino_Id        int64
dtypes: int64(2), str(2)
memory usage: 240.8 MB

## Conversion de tipos de dato

In [7]:
df['Destino_Id'] = df['Destino_Id'].astype('str')
df['Origen_Id'] = df['Origen_Id'].astype('str')
df['Inicio_del_viaje'] = pd.to_datetime(df['Inicio_del_viaje'],format="%Y-%m-%d %H:%M:%S")
df['Fin_del_viaje'] = pd.to_datetime(df['Fin_del_viaje'],format="%Y-%m-%d %H:%M:%S")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7891827 entries, 0 to 7891826
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   Inicio_del_viaje  datetime64[us]
 1   Fin_del_viaje     datetime64[us]
 2   Origen_Id         str
 3   Destino_Id        str
dtypes: datetime64[us](2), str(2)
memory usage: 240.8 MB

## Verificacion de nulos

In [8]:
display(df.isna().sum())
df.isnull().sum()

Inicio_del_viaje    0
Fin_del_viaje       0
Origen_Id           0
Destino_Id          0
dtype: int64

Inicio_del_viaje    0
Fin_del_viaje       0
Origen_Id           0
Destino_Id          0
dtype: int64

## Exploración de datos

### Frecuencia de ubicacion de origen por dia

In [9]:
origenes_pivot = (
    df.groupby([
        df['Inicio_del_viaje'].dt.date,
        'Origen_Id'
    ])
    .size()
    .unstack(fill_value=0)
)

origenes_pivot.head()

Origen_Id,10,100,101,102,103,104,105,106,107,108,...,87,88,9,91,92,93,94,95,96,98
Inicio_del_viaje,,,,,,,,,,,,,,,,,,,,,
2025-01-01,12,5,3,7,3,0,4,6,1,7,...,8,6,5,1,4,4,2,0,7,8
2025-01-02,33,10,3,24,11,0,12,18,7,31,...,21,24,35,1,12,7,11,9,20,8
2025-01-03,34,16,2,31,20,0,12,12,3,28,...,16,30,34,4,16,11,13,6,21,13
2025-01-04,32,3,2,20,6,0,13,11,3,8,...,20,16,25,5,10,12,7,5,11,8
2025-01-05,26,4,0,23,4,0,8,14,8,14,...,18,16,15,9,8,10,12,3,12,8

### Frecuencia de ubicacion de destino por dia

In [10]:
destinos_pivot = (
    df.groupby([
        df['Inicio_del_viaje'].dt.date,
        'Destino_Id'
    ])
    .size()
    .unstack(fill_value=0)
)

destinos_pivot.head()

Destino_Id,10,100,101,102,103,104,105,106,107,108,...,87,88,9,91,92,93,94,95,96,98
Inicio_del_viaje,,,,,,,,,,,,,,,,,,,,,
2025-01-01,7,4,2,6,3,0,4,4,1,11,...,1,4,9,3,2,4,8,1,8,5
2025-01-02,39,8,1,27,17,0,14,14,5,31,...,17,15,36,2,10,6,16,6,12,9
2025-01-03,36,13,3,23,12,0,12,19,3,20,...,15,14,31,7,14,9,15,6,11,8
2025-01-04,38,5,3,17,8,0,8,6,2,3,...,12,12,35,4,8,9,10,3,12,7
2025-01-05,26,2,1,22,7,0,9,9,6,14,...,10,14,13,5,4,9,17,4,8,7

### Frecuencia origen-destino

In [11]:
od = (
    df.groupby([
        df['Inicio_del_viaje'].dt.hour,
        'Origen_Id',
        'Destino_Id'
    ])
    .size()
    .reset_index(name='viajes')
)

od.head()

   Inicio_del_viaje Origen_Id Destino_Id  viajes
0                 0        10         10      15
1                 0        10         12       2
2                 0        10        151       1
3                 0        10        156       3
4                 0        10        157       2